/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/safety`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/check-in` | `/check-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/inventory` | `/inventory`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/steps` | `/steps`; params?: Router.UnknownInputParams; } | { pathname: `/inventory/new`; params?: Router.UnknownInputParams; } | { pathname: `/inventory/[id]/actions`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/inventory/[id]/clarify`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/inventory/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/inventory/[id]/review`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/safety`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/check-in` | `/check-in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/inventory` | `/inventory`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/steps` | `/steps`; params?: Router.UnknownOutputParams; } | { pathname: `/inventory/new`; params?: Router.UnknownOutputParams; } | { pathname: `/inventory/[id]/actions`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/inventory/[id]/clarify`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/inventory/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/inventory/[id]/review`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/safety${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/check-in${`?${string}` | `#${string}` | ''}` | `/check-in${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/inventory${`?${string}` | `#${string}` | ''}` | `/inventory${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/steps${`?${string}` | `#${string}` | ''}` | `/steps${`?${string}` | `#${string}` | ''}` | `/inventory/new${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/safety`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/check-in` | `/check-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/inventory` | `/inventory`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/steps` | `/steps`; params?: Router.UnknownInputParams; } | { pathname: `/inventory/new`; params?: Router.UnknownInputParams; } | `/inventory/${Router.SingleRoutePart<T>}/actions${`?${string}` | `#${string}` | ''}` | `/inventory/${Router.SingleRoutePart<T>}/clarify${`?${string}` | `#${string}` | ''}` | `/inventory/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/inventory/${Router.SingleRoutePart<T>}/review${`?${string}` | `#${string}` | ''}` | { pathname: `/inventory/[id]/actions`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/inventory/[id]/clarify`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/inventory/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/inventory/[id]/review`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
